### ISSUE TITLE
unable to build image locally

### ISSUE THREAD

**Issue by pvj** [takumaw/moinmoin-docker#1]
Hi there, 

First of all, thanks for packing this together! I would like to use it as a basis for an internal wiki so I've tried a test-deploy to Heroku that failed. So I tried to build it locally and it has failed as well.

```>  docker build -t gmoin .
Sending build context to Docker daemon  59.39kB
Step 1/18 : FROM python:2.7
 ---> 92c086fc9702
Step 2/18 : ENV MOINMOIN_VERSION 1.9.9
 ---> Running in c2d1b78a4858
Removing intermediate container c2d1b78a4858
 ---> de26a85e4b80
Step 3/18 : RUN groupadd -r moin && useradd -r -g moin moin
 ---> Running in b534a62b8d96
Removing intermediate container b534a62b8d96
 ---> ce06f2acdf51
Step 4/18 : RUN set -ex 	&& pip install --no-cache-dir "moin==$MOINMOIN_VERSION" 	&& mkdir -p /usr/local/moin 	&& chown -R moin:moin /usr/local/moin
 ---> Running in 4a9a9f7fe3bc
+ pip install --no-cache-dir moin==1.9.9
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting moin==1.9.9
  Downloading https://files.pythonhosted.org/packages/ce/a5/6a304c1e9ec10b38979540f7f95543d1b1c88d58f708ad74ddc430649b68/moin-1.9.9.tar.gz (37.2MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-M0sAJt/moin/setup.py", line 355, in <module>
        setup(**setup_args)
      File "/usr/local/lib/python2.7/distutils/core.py", line 124, in setup
        dist.parse_config_files()
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 702, in parse_config_files
        self._parse_config_files(filenames=filenames)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 599, in _parse_config_files
        (parser.read_file if six.PY3 else parser.readfp)(reader)
      File "/usr/local/lib/python2.7/ConfigParser.py", line 324, in readfp
        self._read(fp, filename)
      File "/usr/local/lib/python2.7/ConfigParser.py", line 479, in _read
        line = fp.readline()
      File "/usr/local/lib/python2.7/codecs.py", line 314, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 57: invalid start byte
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-M0sAJt/moin/
The command '/bin/sh -c set -ex 	&& pip install --no-cache-dir "moin==$MOINMOIN_VERSION" 	&& mkdir -p /usr/local/moin 	&& chown -R moin:moin /usr/local/moin' returned a non-zero code: 1
```

Do you happen to have the bandwith to take a look and help? 

Engine v18.09.2
Machine v0.16.1

Let me know if you need any other info. Thanks, cheers, 

Janos

**Comment by abejaranoh** [comment]
Hi, I run "docker build ." but got this error. Seems to be similar

 => ERROR [3/7] RUN set -ex  && pip install --no-cache-dir "moin==1.9.10"  && mkdir -p /usr/local/moin  && chown -R moin:moin /usr/local/moin

any ideas?

**Comment by abejaranoh** [comment]
Hi @pvj , i created a pull request that one should work #3

**Comment by pvj** [comment]
Thanks! I have totally forgot about this PR and haven't had time to solve this then or now. It is great to hear from you that you could update the D'rfile and I ran your solution and it has worked.
